---
abstract: 'A safer HTTP::Tiny'
author:
  - 'Robert Norris <rob@eatenbyagrue.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Tiny-Paranoid
requires:
  Carp: '0'
  Class::Method::Modifiers: '0'
  HTTP::Tiny: '0.039'
  Net::DNS::Paranoid: '0'
resources:
  bugtracker: https://github.com/robn/HTTP-Tiny-Paranoid/issues
  repository: git://github.com/robn/HTTP-Tiny-Paranoid.git
version: '0.03'
